### ISSUE TITLE
Feature Request: show hyperlink urls

### ISSUE THREAD

**Issue by ericnewton76** [ChangemakerStudios/Papercut-SMTP#145]
**Is your feature request related to a problem? Please describe.**
I would love to be able to see the hyperlink url before clicking it.

**Describe the solution you'd like**
- On hover over a hyperlink, show the hyperlink url somewhere.  Chrome shows it in the lower left corner of the window.  
- On rightclick of the hyperlink, a context menu, including "Copy Link Location" for inspection in notepad/etc

**Comment by cdroulers** [comment]
This would be a great feature, one of the most frequent action I take in Papercut is trying to open a link in an incognito window, which I can't because it won't let me copy it easily!

**Comment by woutervs** [comment]
I would also love the "Copy link" feature, is this something that is in de pipeline? 

Kind regards.

**Comment by demacryx** [comment]
A feature to click on HTML encoded links would be also awesome. because for some reason it shows the link with \&amp;\ signs. which breaks the link and makes it useless.

**Comment by 1Jesper1** [comment]
@Jaben I would like to create this, do you have any advice for the place of the code and methods to use?

**Comment by 1Jesper1** [comment]
@CrovLune What is the specific HTML encoded link?

**Comment by CrovLune** [comment]
@1Jesper1 I can't find it anymore. It's been a long time. But SMTP sent me not an actual HTML link that could be clicked on in the mail. But rather a link with &amp and other stuff... Which meant that you had to copy the link, edit it manually and then paste it in browser to open it. Which was annoying as hell.

**Comment by Jaben** [comment]
> 
> 
> @Jaben I would like to create this, do you have any advice for the place of the code and methods to use?
> 
>     1. _On hover over a hyperlink, show the hyperlink url somewhere. Chrome shows it in the lower left corner of the window._
>        What should be prefered? Set an onmouseover attribute on <a tags on message render? Or use something like this [social.msdn.microsoft.com/Forums/en-US/6f292ac0-ccbf-4fc1-88a5-e3b9ea8d862a/webbrowser-mouse-events?forum=Vsexpressvcs](https://social.msdn.microsoft.com/Forums/en-US/6f292ac0-ccbf-4fc1-88a5-e3b9ea8d862a/webbrowser-mouse-events?forum=Vsexpressvcs) [stackoverflow.com/a/3114319/2908623](https://stackoverflow.com/a/3114319/2908623)
> 
>     2. _On rightclick of the hyperlink, a context menu, including "Copy Link Location" for inspection in notepad/etc_
>        We don't want to use the default contextmenu? Do we have to create a custom contextmenu/ dropdown?
> 
>     3. _A feature to click on HTML encoded links would be also awesome. because for some reason it shows the link with &\ signs. which breaks the link and makes it useless._
>        I think we need to use _WebUtility.HtmlDecode_ in the Navigate method?

I've switched Papercut to use Edge (WebView2) -- it's currently in branch "NewHTMLRender". The problem is currently handling the installation system with the edge download.

Yeah, I'd like to see a custom menu: go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by 1Jesper1** [comment]
@Jaben Good work!
1. For showing the url in the edge of the screen we could enable IsStatusBarEnabled: `coreWeb.Settings.IsStatusBarEnabled = true;`
2. For custom contextmenu we could maybe use this: https://stackoverflow.com/a/62732034/2908623 ? We need to use a Form for a ContextMenuStrip.
3. I think the HTML encoded links work already.

**Comment by Jaben** [comment]
@1Jesper1 Choosing option #1 for now. Seems to work fine. Thanks for your help!
