### ISSUE TITLE
Forwarding from papercut, save configuration

### ISSUE THREAD

**Issue by ericnewton76** [ChangemakerStudios/Papercut-SMTP#147]
**Is your feature request related to a problem? Please describe.**
Store the forwarding options between uses

**Describe the solution you'd like**
Store the smtpserver/port/user login credentials between use.

**Additional context**
I use the forward feature during development to show project manager and the client, what the content of the email will be.  This makes it easier than having to wait for UAT cycle to get feedback.  Thanks.

**Comment by baldsimon** [comment]
I think you can create a rule to forward emails based on specific criteria.
In my experience, if you close the application cleanly, after creating the
rules, they are saved as a JSON object and reloaded when you load papercut
again.

Simon.

**Comment by 1Jesper1** [comment]
Hello @ericnewton76 Is this still a problem?
