### ISSUE TITLE
Linux Version?

### ISSUE THREAD

**Issue by trymeouteh** [ChangemakerStudios/Papercut-SMTP#149]
Please make a Linux version that can work with XAMPP or the LAMPP stack (Apache, MySQL, PHP, PHPMyAdmin) and have it be an AppImage or a Flatpak for easy install on all Linux distros.

This software works great, on Windows, it is open source and I will like to continue using it on Linux as I am leaving Windows for Linux!

**Comment by sphereweb83** [comment]
Also interested in a Unix version

**Comment by albertcito** [comment]
Also interested in Mac version 🙏

**Comment by c0d3r1010** [comment]
Mac option would be awesome!

**Comment by MashRoofa** [comment]
Yep a Mac version will be of great help!

**Comment by ctwoodwa** [comment]
Thumbs up for a Mac version

**Comment by Jaben** [comment]
I'll transition to MAUI UI here soon hopefully -- I don't have a MAC to do testing on, though.

**Comment by snovak7** [comment]
What about service option for Mac & Linux ? Without the GUI, since it has also the web UI?

**Comment by maleu1** [comment]
Interested in both Linux and Mac as well.

**Comment by roboter** [comment]
+1 for MAUI/MAC version, can help with MAC setup/test.

**Comment by Jaben** [comment]
There is now a docker version that supports linux and mac.
