### ISSUE TITLE
Memory consumption and CPU load loading 1000s of mails

### ISSUE THREAD

**Issue by adymorz** [ChangemakerStudios/Papercut-SMTP#150]
**Problem**
I am frustrated about the loading time and memory consumption when loading a lot of mails. It takes the application more than 40 minutes to load ~~a few 1000~~ 113'621 mails.

**Solution**
I would like to see that papercuts loads the mails lazy. I would love to see the interface of the application and wait for the mails to be loaded, meanwhile having the option to delete all mails.
I would recommend to load only the actual selected mail into memory, while having a list of small representations of the relevant information of all the mails in memory.

**Alternatives I have considered**
As a workaround I could simply delete the mail files from the folder they are stored in. ~~But I do not remember the folder name, where the mails are stored in.~~ Found it: `C:\Program Files (x86)\Changemaker Studios\Papercut\Incoming`
I also could change the configuration of our software to not send emails during automated test, but then I would loose the option to look at the mails which have been sent if something goes wrong.

**Task manager during loading**

![grafik](https://user-images.githubusercontent.com/1993680/61960791-769e9300-afc6-11e9-9967-580c8f886922.png)

![grafik](https://user-images.githubusercontent.com/1993680/61961622-0f81de00-afc8-11e9-8824-2529d7c322dc.png)

![grafik](https://user-images.githubusercontent.com/1993680/61962366-9be0d080-afc9-11e9-9ce4-e41fb00ccb2b.png)

![grafik](https://user-images.githubusercontent.com/1993680/61962965-09413100-afcb-11e9-9366-5c30c3680b30.png)

**Comment by baldsimon** [comment]
I run a daily batch file to move yesterday’s emails out to a compressed
folder, named for yyyy-mm-dd. This keeps paper cut responsive and ensures
that I have the emails to go back to if they’re needed.

S.

**Comment by Jaben** [comment]
Latest changed loading and logging (internally) -- the situation will hopefully improve.

**Comment by Jaben** [comment]
Closing this for now as I think the situation has improved and there has been no responses back.
