### ISSUE TITLE
Disable notification

### ISSUE THREAD

**Issue by majkinetor** [ChangemakerStudios/Papercut-SMTP#161]
**Is your feature request related to a problem? Please describe.**
Its somewhat a problem. I run automatic tests and papercut is used as a test mail server for backend app. During development I am flood with notifications.

**Describe the solution you'd like**
Add option in configuration file `EnableNotifications` by default `true`.

**Describe alternatives you've considered**
The only alternative is to Focus Assist. If there is no one, you can turnd down the volume and ignore the popups.

**Comment by majkinetor** [comment]
BTW, it would also be cool to setup Log folder location. I use portable version that is commited directly on repository. Papercut keeps log open and that prevents my GitLab to remove file, so builds break.

**Comment by richardlawley** [comment]
You don't need to use Focus Assist for this - you can simply disable notifications from Papercut in Windows (right click a notification, Turn off all notifications for Papercut (or Settings app in Windows > Notifications & actions).

**Comment by majkinetor** [comment]
Yeah, the down side is that everybody needs to do that.

**Comment by 1Jesper1** [comment]
@Jaben I would like to create this, do you have any advice for the place of the code and methods to use?

**Comment by richardlawley** [comment]
@1Jesper1 I actually looked at this previously but never got round to packaging it up.  Submitted PR for it.

**Comment by 1Jesper1** [comment]
@richardlawley Should we create a new issue https://github.com/ChangemakerStudios/Papercut-SMTP/issues/161#issuecomment-619369649 Or just keep this issue open?

**Comment by 1Jesper1** [comment]
@majkinetor I created a pull request for the loggingpath feature: https://github.com/ChangemakerStudios/Papercut-SMTP/pull/193
