### ISSUE TITLE
How to fix "Error 1053:  The Service did not respond..." when attempting to start Papercut Service?

### ISSUE THREAD

**Issue by Picoparker** [ChangemakerStudios/Papercut-SMTP#164]
Installed latest Papercut version on a windows server2016 and when attempting to start the papercut service I get "Error 1053:  The service did not repond to the start or control request in a timely fashion." errom message.

**Comment by Jaben** [comment]
Please look in this directory:

```
C:\ProgramData\Changemaker Studios\Papercut SMTP
```

For .log files. If you find any can you post them here? Thanks.

**Comment by maerger** [comment]
Same issue here - there is no error log in the above folder...

**Comment by maerger** [comment]
Solved for me: the service needs .net 4.7 installed

**Comment by 1Jesper1** [comment]
Hello @Picoparker Has your issue been solved?
