### ISSUE TITLE
Conditional Relay rule

### ISSUE THREAD

**Issue by banachg** [ChangemakerStudios/Papercut-SMTP#165]
**Is your feature request related to a problem? Please describe.**
Want to auto release some mails based on receiver domain.

**Describe the solution you'd like**
A mix of Relay and Conditional Forward functionality where I can set regex for header (to filter domain) so mails that fits this regex are automaticaly released to receiver.

**Describe alternatives you've considered**
Conditional Forward parameter "to Email" could also have a checkbox to use original receiver (will skip CC if sender specified)

**Additional context**
Using your tool on my dev server and I do not want to release message to customer by mistake. But sometimes you want to relese them to group of peoples, For example in your company.

**Comment by ben-garside** [comment]
Hey @banachg 

I have this set up in my environment for this exact reason, all our test applications send to a server running Papercut then we use Conditional Forwarders to release emails to Sendgrid based on a set of criteria.

Using the `Regex Header Match` set the conditional rule to only run on a domain of your choice and then in the `To` and `From` fields just leave it empty, if they are empty Papercut will just take the values from the original email.

**Comment by irve** [comment]
Where can I find to examples or some documentation on this ?
I'm not good at Regex, and want to make a setup where only some receives the emails, but not any customers.

**Comment by 1Jesper1** [comment]
@irve Maybe @ben-garside could help you with an example?

**Comment by Jaben** [comment]
Closing this as the request has been added to Papercut.
