### ISSUE TITLE
Why is the string "3D" showing up all over the text in the Raw view?

### ISSUE THREAD

**Issue by TechSavvySam** [ChangemakerStudios/Papercut-SMTP#168]
**Describe the bug**
I have code that when sending an email to a real server, works correctly and receives the HTML source correctly.

When I send the email to Papercut SMTP, the text is broken randomly onto new lines and the string "3D" is displayed throughout the body.

**this is what is received into exchange/outlook:**
```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"><link href="https://fonts.googleapis.com/css?family=Lato&amp;display=swap" rel="stylesheet">
```

**this is what is displayed in Papercut SMTP Raw:**
```
<!DOCTYPE html>
    <meta name="viewport" content="width=device-width">

<html>
<head>
    <link href=**3D**"https://fonts.googleapis.com/css?family=**3D**Lato&displ=
ay=**3D**swap" rel=**3D**"stylesheet">
    <meta name=**3D**"viewport" content=**3D**"width=**3D**device-width" />
```

**this is what shows up in Papercut SMTP Body**
```
<!DOCTYPE html>

<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width" />
```

**To Reproduce**
1. Send HTML email into Papercut SMTP
2. View email in Papercut SMTP and click on "Raw" tab

**Expected behavior**
Expect proper formatting of HTML received w/o extraneous characters embedded.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 10.0.18362 Build 18362

**Additional context**

**Comment by Jaben** [comment]
Check out this thread for more information: https://stackoverflow.com/questions/4016067/whats-a-3d-doing-in-this-html/4016098#4016098

**Comment by TechSavvySam** [comment]
@Jaben explained why this is not a bug...
