### ISSUE TITLE
Net Framework

### ISSUE THREAD

**Issue by ghost** [ChangemakerStudios/Papercut-SMTP#169]
Hi, just a quick question, can i run the app without netframwork? is it possible?

**Comment by Jaben** [comment]
The current version doesn't support it -- but I have an alpha .NET Core version that does support building into a "self-contained" EXE. Once .NET Core 5 rolls out I'll be ready to seriously move Papercut to .NET Core and "Maui" UI.

**Comment by michaellwest** [comment]
Based on the updated schedule with Maui, I assume the move to .net 6 won't happen until mid-2022.

**Comment by LewisJohnson** [comment]
Well :)

https://devblogs.microsoft.com/dotnet/announcing-net-6/

**Comment by Jaben** [comment]
v7.0 is .NET Core.
