### ISSUE TITLE
I am not able to access the papercut service with my windows server Url. 

### ISSUE THREAD

**Issue by anand0601** [ChangemakerStudios/Papercut-SMTP#171]
**Describe the bug**

I am not able to access the papercut service with my windows server Url. 

**To Reproduce**
1. I have installed the papercut service at one of my Virtual machine like VM1 - and Replaced the ip address with my server name 
<img width="582" alt="PaperCutConfig" src="https://user-images.githubusercontent.com/18432193/89662917-c33bd000-d8a2-11ea-8255-5018ab0e0e94.PNG">

2. when I tried the url  - http://ftc-AAAA:37408/  - its not working.

**Expected behavior**

I want to install papercut application on my windows server and access that url from any other machine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Server 2008 R2 Enterprise 
 - Version : Service Pack 1

**Additional context**
Do we need to change the ip address or keep using the same ip address already in the json config file.
How does it record the email

**Comment by 1Jesper1** [comment]
@anand0601 What if you try localhost:37408 ?

**Comment by lgrant21** [comment]
I was able to get this to work by stopping the service changing the value to the IP not the host name with the service stopped. Then start the service. However, as soon as the service restarts it reverts back to 127.0.0.1.

**Comment by 1Jesper1** [comment]
@Jaben It seems `"IPCommServerIPAddress"` is not used anymore? See [fa116d3abcaefa701f0e70855bf8de8d26acd829](https://github.com/ChangemakerStudios/Papercut-SMTP/commit/fa116d3abcaefa701f0e70855bf8de8d26acd829)

**Comment by Jaben** [comment]
@1Jesper1 Yeah, it's not a secure protocol. Making it listen outside of localhost is not a great idea.

**Comment by 1Jesper1** [comment]
@Jaben Oh, should I delete my PR and make a PR which removes the `IPCommServerIPAddress` prop?

**Comment by Jaben** [comment]
The issue is here is they couldn't figure out how to bind HTTP server to *All* -- which is partly my fault. I don't believe it's related to IPComm at all.

The IPCommServerIPAddress properties are used.

**Comment by 1Jesper1** [comment]
@Jaben Could you point me to the place `IPCommServerIPAddress ` is used?

**Comment by Jaben** [comment]
IPCommServer* is not used, my bad.

PapercutIPCommEndpoints.cs uses 'IPCommServiceIPAddress'. The PR #219 is not needed as the endpoint values already come from the json settings.

**Comment by Jaben** [comment]
IPCommServer* is not used, my bad.

PapercutIPCommEndpoints.cs uses 'IPCommServiceIPAddress'. The PR #219 is not needed as the endpoint values already come from the json settings.

**Comment by 1Jesper1** [comment]
@Jaben I will remove the PR, but do we need to create a PR which removes the IPCommServerIPAddress  property?

**Comment by Jaben** [comment]
@anand0601 Please try latest release. @1Jesper1 thanks but it's already removed.

**Comment by Jaben** [comment]
reopen if the problems persist.
