### ISSUE TITLE
Embedded images not displaying

### ISSUE THREAD

**Issue by StevePritchard** [ChangemakerStudios/Papercut-SMTP#173]
I'm not sure whether this is a Papercut-SMTP issue, or a problem with the way that I'm compiling my email. All I know is that if I send the email to gmail, then it displays as I intended, but Papercut-SMTP doesn't show my attached images.

Inside my email body, I have markup like this:

<img src="cid:ed5282b5Xb505X4d35Xb071X2a8e6224bbd5" />

And inside the Raw content of my email I can see:

----boundary_0_5273848a-b738-4149-91f7-5acb36f848bc
Content-Type: image/jpg
Content-Transfer-Encoding: base64
Content-Disposition: inline
Content-ID: <ed5282b5Xb505X4d35Xb071X2a8e6224bbd5>

/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8U
HRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgN
DRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIy
...

However, the image isn't rendered correctly in Papercut-SMTP, and I just get a standard missing image "X" instead.

Is there a problem with the way I'm preparing my email content, or does Papercut-SMTP have a problem displaying attachments inline?

Cheers,

Steve.

**Comment by Jaben** [comment]
Please attach the EML file and I can take a look.

**Comment by PrasadKhandekar** [comment]
Here is a sample file for your review.
[20210416173541472 Admin User Password Creation! be9c82.txt](https://github.com/ChangemakerStudios/Papercut-SMTP/files/6328862/20210416173541472.Admin.User.Password.Creation.be9c82.txt)

**Comment by 1Jesper1** [comment]
@PrasadKhandekar It seems to be a jpeg file, also only the base64 string should be included, the data: should be removed.
See: 
[working.txt](https://github.com/ChangemakerStudios/Papercut-SMTP/files/6718958/working.txt)

**Comment by Jaben** [comment]
Please try latest v7.0 release. Closing this issue.
