### ISSUE TITLE
Email not retrieve when # sign in Subject line

### ISSUE THREAD

**Issue by thom1904** [ChangemakerStudios/Papercut-SMTP#174]
**Describe the bug**
I have a third party application configured to send emails to the Papercut service running on a Windows 2012 server.  This application places a number in the subject line prefixed by a #.  The email is received and stored on the file system.  It shows in the web UI.  When the item is clicked in the web UI, the email appears to not be parsed correctly.  The Subject is the only information that shows.  No headers and no sections even though this email has an attachment. 

**To Reproduce**
Send an email into the Papercut service with an # in the subject line.

**Expected behavior**
It would be expected that the email be parsed correctly showing headers and sections.
**Screenshots**
![image](https://user-images.githubusercontent.com/74431772/99119981-17ec9680-25c8-11eb-97ee-4e7ccd96de8e.png)

**Desktop (please complete the following information):**
Papercut service being used not the desktop application
 - OS: Windows Server
 - Version 2012 R2

**Additional context**
If the # is removed from the file name saved on disk,  the email is parsed and displayed as expected.

**Comment by ryan-warrener** [comment]
I have made a fix for this on a forked repo. You can either build it or just download the zip file here: https://github.com/ryan-warrener/Papercut-SMTP/releases/tag/5.7.1

It has saved us a lot of pain!

**Comment by 1Jesper1** [comment]
https://github.com/ChangemakerStudios/Papercut-SMTP/pull/180 I see the fix has been merged.
