### ISSUE TITLE
Support enhanced status codes if EHLO used rfc 2034

### ISSUE THREAD

**Issue by gkelley-fmb** [ChangemakerStudios/Papercut-SMTP#176]
I'm using papercut to test email code and the response codes aren't as expected. See https://tools.ietf.org/html/rfc2034

**Comment by 1Jesper1** [comment]
What do we need to do to support this?

**Comment by gkelley-fmb** [comment]
I apologize this was a poorly written ticket request. I was working with code that made use of the smtp extension Enhanced-Status-Codes where 250 responses had a more granular status code. See Section 6 example [here](https://datatracker.ietf.org/doc/html/rfc2034#section-6) if you are inclined. As this is a proposal I don't believe any time needs spent on it. At the time it would have been a nice feature.
