### ISSUE TITLE
Change directory Papercut watches?

### ISSUE THREAD

**Issue by jzabroski** [ChangemakerStudios/Papercut-SMTP#178]
**Is your feature request related to a problem? Please describe.**
We stopped using network interception for papercut and switched to using drop copies, e.g. our App.Config is now:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.net>
    <defaultProxy useDefaultCredentials="true" />
    <mailSettings>
      <smtp deliveryMethod="SpecifiedPickupDirectory">
        <specifiedPickupDirectory pickupDirectoryLocation="d:\data\smtp" />
      </smtp>
    </mailSettings>
  </system.net>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
</configuration>
```

Our old App.Config was:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.net>
    <defaultProxy useDefaultCredentials="true" />
    <mailSettings>
      <smtp>
	      <network defaultCredentials="true" host="localhost" port="25" />
      </smtp>
    </mailSettings>
  </system.net>
  <startup useLegacyV2RuntimeActivationPolicy="true">
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.1" />
  </startup>
</configuration>
```

**Describe the solution you'd like**
The Papercut GUI is a fantastic tool for reading eml files.  I would like to be able to configure it to use a FileSystem Watcher and load any emails drop copied into that folder, without needing to run a network proxy to intercept emails.

**Describe alternatives you've considered**
Stop using Papercut and look for a different tool?

**Additional context**
Love this product

**Comment by jzabroski** [comment]
@Jaben It looks like https://github.com/ChangemakerStudios/Papercut-SMTP/blob/58e08eca4f59052c102a4e1d364bf7687a2b82cc/src/Papercut.Core/Domain/Paths/MessagePathConfigurator.cs#L49-L62
and
https://github.com/ChangemakerStudios/Papercut-SMTP/blob/58e08eca4f59052c102a4e1d364bf7687a2b82cc/src/Papercut.Core/Domain/Paths/MessagePathConfigurator.cs#L74

is where Papercut UI watches for file system changes and determines where the default save path is.

If there was a configuration setting added to this and some small local storage used in the user's AppData directory, it would be easy to configure and expose a File Chooser Dialog to change the directory.

Thoughts?

**Comment by jzabroski** [comment]
BTW, the whole reason I am interested in this, is it seems your email viewer works better than Outlook at viewing emails generated from .NET Framework context.  If I use .NET Core and MikeKit, Outlook works great...

**Comment by Jaben** [comment]
@jzabroski I'm a little confused by this request: Papercut already watches the directory for changes. If you drop EML files in there they will appear.

Also the directory locations are ALREADY configurable via settings.

I'm not sure what you're asking for here...

**Comment by jzabroski** [comment]
Hmm... I will need to look again. I didn't see a place where I could configure it to save to d:\data\smtp

I clearly dove into the code to try to figure this out, so I'll start there.

For context, you handle EML files better than Outlook does, so I want to use just the GUI without the proxy.

**Comment by Jaben** [comment]
@jzabroski It's not in the code, it's in the configuration file: Papercut.exe.config. MessagePaths:

![image](https://user-images.githubusercontent.com/448726/121282166-0beb5d80-c8a7-11eb-935a-61f21dda7bde.png)

Add your path onto the end:

```
%ApplicationData%\Changemaker Studios\Papercut SMTP;%ApplicationData%\Papercut;%BaseDirectory%\Incoming;%DataDirectory%\Incoming;d:\data\smtp
```

**Comment by jzabroski** [comment]
@Jaben Thank you.  I installed Papercut via Chocolatey package "[papercut](https://community.chocolatey.org/packages/papercut)" and none of the programs installed appear to have an App.config file! Somewhat shocking/confusing.  It looks like I installed it on April 28, 2020.

**Comment by Jaben** [comment]
Please open an issue for that problem.

I hate maintaining the Chocolatey package. Since I don't get paid squat to write open source, I don't do things I hate much.

**Comment by Jaben** [comment]
For now this isn't an issue as a support situation that found a possible new task -- closing for now.
