### ISSUE TITLE
Message not rendering when '#' character in message filename 

### ISSUE THREAD

**Issue by ryan-warrener** [ChangemakerStudios/Papercut-SMTP#179]
**Describe the bug**
An email message will not display in the HTTP front-end when the message filename has a '#' character in it

**To Reproduce**
1. Send an email through the Papercut SMTP server with the subject being "#" and the body being "test"
2. Go to 'http://localhost:37408' to view your email inbox
3. Click on the email you just sent, which will be displayed as '#'
4. See that there is no email content displayed, there is no "HTML" and "Plain Text" tabs, and the "From", "To", "Date" fields are not displayed

**Expected behavior**
The email message body, the "From", "To", "Date" fields and the "HTML" and "Plain Text" tabs should be displayed when clicking on the email

**Screenshots**
Here is how the email message is rendered when the '#' character is in the message filename:
![image](https://user-images.githubusercontent.com/6075252/104519133-0cabfa80-564d-11eb-9543-e99919dbff94.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
This only occurs if a '#' symbol is in the physical filename of the email message (.eml file). Since the filename uses a truncated version of the subject of the email, the bug will not occur if the '#' character is beyond the limits of the truncated subject name

**Comment by Jaben** [comment]
PR with fix merged.

Thank you!
