### ISSUE TITLE
delete button does not expand based off selected email count

### ISSUE THREAD

**Issue by jwilburn** [ChangemakerStudios/Papercut-SMTP#181]
using latest release (Papercut.5.7.0)

1. configure Papercut to intercept emails
2. have some process generate hundreds of emails
3. select all the emails
4. the _DELETE_ button text starts to cut off with larger numbers (picture attached)

![papercut](https://user-images.githubusercontent.com/5719336/107989399-d937f500-6f97-11eb-89d9-3e6168089254.png)

**Comment by rfverbruggen** [comment]
Hi @jwilburn, 

I've submitted pull request #185 to resolve this issue, hopefully it will be accepted and included in the next release.

You could always download my repository and (re)build the solution to get the functionality right now.

Kind regards,

Robbert Verbruggen
