### ISSUE TITLE
High CPU and memory usage

### ISSUE THREAD

**Issue by Spinks90** [ChangemakerStudios/Papercut-SMTP#182]
**Describe the bug**
I know I'm using it out of the scope of what Papercut was intended for. I'm using it in a production environment for legacy software which we don't have the source to capture the e-mails and forward them onto our SMTP so we can see the issues with the software.

Let's say we get around 1,000 per day send out and it just continues to build up. There small e-mails with a few lines of text or exception message.
 
Here is a screenshot of trying to load Papercut up 
![image](https://user-images.githubusercontent.com/63308868/111146741-ae829180-8581-11eb-9b2d-d356e9744875.png)

The main application is stuck loading, usually takes a good few hours before it sorts itself out:
![image](https://user-images.githubusercontent.com/63308868/111146011-dae9de00-8580-11eb-8515-7b32c2864a09.png)

I've created a DMP file of the process if you want me to send you it.

**Environment:**
- Papercut version 5.7.0 (Latest)
- Windows Server 2016
- 32GB
- Intel Xeon E5-2697 v3 x2

EDIT:
Looked into the issue more by using Process Monitor to see where files are been loading from and found they're been loaded from `C:\ProgramData\Changemaker Studios\Papercut SMTP\Incoming` and I've deleted them all from there and it's back happy. There were 110K odd e-mails there.

My IT technician was supposed to delete them every few weeks using Papercut GUI which he claims he has been doing but I tried it on a smaller amount of emails after clearing that folder and it works fine. I'll let it build up for a week and try myself and check that directory to see if they all do get deleted, if they don't, I'll report it an bug.

I'll leave this ticket open as I don't think 110K e-mails should really take up so much memory but it's not an issue, as I'm probably the only one with so many e-mails. Lol.

Anyways, would it be possible to add data retain option? Can always make a new ticket for that feature.

**Comment by Jaben** [comment]
Is the situation any better in the latest version 6?

**Comment by Jaben** [comment]
Please try latest and reopen this issue if the problem persists.
