### ISSUE TITLE
Outgoing connection when mail received

### ISSUE THREAD

**Issue by josiasdx** [ChangemakerStudios/Papercut-SMTP#184]
Is not really a issue but a question:
When receive an email, papercut creates a connection to 142.250.514.170:443 
If this is for local purpouses, can't understand why an outgoing connection...
Thank you

**Comment by Jaben** [comment]
If you're making these types of accusations you need to supply evidence "Josías Moreno" (if that's your real name). What did you use to see that activity? Where are the screen shots? Did you look up what the IP address is?

To state the obvious for others: Papercut does not send email anywhere except where you've configured it. The project has been around for 8 years with hundreds of thousands of download by *software developers*. All the code is open source.

**Comment by josiasdx** [comment]
No accusations, just want to understand. I really love this software, but once a day receive the alert from firewall (netlimiter.com) telling this. I block the outgoing connection and still working fine.
I created a rule in firewall to block this. Now I deleted the rule and seems not to happen anymore. It is strange. If I notice again, I will post an screenshot
Thank you for answering

**Comment by josiasdx** [comment]
The output address is the google IP (192.217.17.10)
Here an screenshot:
https://ibb.co/wCJmG5h

My congratulations for your app. It is really great.
Just want to understand about this behaviour
