### ISSUE TITLE
Change ""delete all" buttons to uppercase or use capital letter at the beginning

### ISSUE THREAD

**Issue by 1Jesper1** [ChangemakerStudios/Papercut-SMTP#186]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/4539406/114701427-182dc100-9d23-11eb-8330-5855efe80c70.png)

**Describe the solution you'd like**
Please change to Proceed and Cancel instead of all lowercase.

**Describe alternatives you've considered**
All uppercase.

**Comment by Jaben** [comment]
This is a convention in MahApps. I'm not sure how to change it. You can see it in the code here:

![image](https://user-images.githubusercontent.com/448726/121106148-76cb6480-c7d3-11eb-858c-45c0b39599d9.png)

**Comment by 1Jesper1** [comment]
What style does the "Forward" and the "Delete" buttons have? These buttons have all uppercase characters.

**Comment by Jaben** [comment]
I don't know. You're welcome to make changes and submit a PR if you feel strongly. My goal to move the UI to something newer here soon.

**Comment by Jaben** [comment]
Thanks for the PR -- closing this issue.
