### ISSUE TITLE
Always show border for windows

### ISSUE THREAD

**Issue by 1Jesper1** [ChangemakerStudios/Papercut-SMTP#188]
**Is your feature request related to a problem? Please describe.**
Border of windows are not shown?

![image](https://user-images.githubusercontent.com/4539406/123474843-dc548900-d5fa-11eb-96b1-f75195f0cfd1.png)

**Describe the solution you'd like**
I would like to always see the borders of the window.
![image](https://user-images.githubusercontent.com/4539406/123474747-b5965280-d5fa-11eb-80d8-48382f6ceaee.png)

**Describe alternatives you've considered**
Does it have something to do with Aero peek? 
`_isAeroEnabled` check in `UIHelper.cs`?

I added  ` BorderBrush="{DynamicResource MahApps.Brushes.Accent}"` to `RulesConfigurationView.xaml` to show the border.

**Comment by abejenaru** [comment]
I have the same issue, look & feel is too flat, I would appreciate if it looked more like native GUI applications.
