### ISSUE TITLE
SVG image size is ignored

### ISSUE THREAD

**Issue by lumin888** [ChangemakerStudios/Papercut-SMTP#197]
**Describe the bug**
I have a HTML email with an embedded SVG image and the width attribute specified in HTML.

It seems Papercut will render the image using the size defined in the SVG, rather than the HTML.

**To Reproduce**
A snippet of the HTML:
`<img height="auto" src="https://example.com/image.svg" style="border:0;display:block;outline:none;height:auto;width:100%;" width="80">`

**Expected behavior**
When the .eml file is opened with Thunderbird, the SVG image renders correctly. So I guess the expected behaviour is that it renders the same as Thunderbird.

I would have expected the HTML attributes have precedence over those defined in the SVG?

**Desktop:**
 - OS: Windows 10
 - Papercut v5.8.0

**Comment by 1Jesper1** [comment]
Do you have screenshots to show the difference?

**Comment by lumin888** [comment]
Thanks for responding. Unfortunately I do not and have changed my project to use PNGs instead. I will close this issue for the time being.
