### ISSUE TITLE
Log panel is hidden

### ISSUE THREAD

**Issue by firepolo** [ChangemakerStudios/Papercut-SMTP#198]
**Describe the bug**
The log panel is behind the message panel.

**To Reproduce**
1. Click on the Log button in top
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/1777148/136412070-b1719347-3e76-498a-942b-32b985217724.png)

**Desktop**
 - OS: Windows 10 Home
 - Version: 21H1
 - OS build: 19043.1237

**Comment by 1Jesper1** [comment]
What version of Papercut do you use?

**Comment by Jaben** [comment]
You still having this problem with Papercut v6?

**Comment by idblew** [comment]
Can confirm this issue running Papercut V6

![image](https://user-images.githubusercontent.com/16039175/149682639-a25a0482-c06f-4726-b8d3-a16023217d96.png)

**Comment by 1Jesper1** [comment]
Thanks, I can reproduce the bug!
1. Remove readme mail in messages.
2. Restart Papercut.
3. Open log.
cc @Jaben

**Comment by Jaben** [comment]
Please try latest and reopen this issue if the problem persists.
