### ISSUE TITLE
Chocolatey package missing for recent releases

### ISSUE THREAD

**Issue by gep13** [ChangemakerStudios/Papercut-SMTP#201]
**Describe the bug**

The most recent version of Papercut on Chocolatey is 5.8.0, but there is a more recent version 6.0.0 available.  Is there a reason that this hasn't been pushed as a Chocolatey package?

**To Reproduce**

1. choco install papercut
2. Only version 5.8.0 is installed

**Expected behavior**

I can install the latest version of Papercut using Chocolatey

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**

If you need any help with the Chocolatey package, let me know.  I work for Chocolatey :smile:

**Comment by Jaben** [comment]
Okay -- I deployed it. Hopefully it works.
