### ISSUE TITLE
Smtp Server does not run on Windows 11

### ISSUE THREAD

**Issue by snovak7** [ChangemakerStudios/Papercut-SMTP#206]
When running either Service or Smtp (Client), I cannot send any email to local smtp port

when I am running from PowerShell it stops here, and doesn't continue
[19:34:59 INF] Starting Smtp Server on 0.0.0.0:25...

This should pass the above point.

**Desktop (please complete the following information):**
Windows 11 (Version 21H2 OS Build 22000.376)

**Comment by Jaben** [comment]
I currently don't have a Windows 11 test machine. My first thought is a permission problem. Please run the terminal as administrator and see if that works.

**Comment by snovak7** [comment]
Well I did all I could, so I exhausted my resources. I did allow some permissions for network, but it kind of stalls at opening. I did remember I somehow manually could run, but then when I returned after a month, I forgot. It would be good to somehow fix this, and that there would be a solution to it.

As a workaround I found the docker version of some fork which is ported to Core version, which can run in docker...

**Comment by Jaben** [comment]
Yeah that's the version I'm working on now. I'm also improving the web 
email ui.

**Comment by michael-freidgeim-webjet** [comment]
> As a workaround I found the docker version of some fork which is ported to Core version, which can run in docker...
Where can I find  the docker version?

**Comment by bangush** [comment]
Working on Microsoft Windows [Version 10.0.22621.1265]

**Comment by snovak7** [comment]
@michael-freidgeim-webjet https://hub.docker.com/r/jijiechen/papercut

**Comment by Kissaki** [comment]
Papercut runs fine on Windows 11 for me. It's not a general Windows 11 issue. *(Which behaves like Windows 10 in pretty much everything.)*

<details><summary>log…</summary>
```
11.06.2024 21:09:46 [Information] IPComm Server Ready: Listening for New Connections at "127.0.0.1:37402"
11.06.2024 21:09:46 [Information] Attempting to Load Rules from "C:\Program Files (x86)\Papercut SMTP\rules.json" on AppReady
11.06.2024 21:09:46 [Information] Starting Smtp Server on "0.0.0.0":25...
11.06.2024 21:09:45 [Information] Papercut Backend Service is not running. SMTP enabled in UI.
11.06.2024 21:09:43 [Information] Setting WebView2 User Data Folder: "C:\Users\redacted\AppData\Roaming\Changemaker Studios\Papercut SMTP\WebView2"
11.06.2024 21:09:43 [Information] Setting WebView2 User Data Folder: "C:\Users\redacted\AppData\Roaming\Changemaker Studios\Papercut SMTP\WebView2"
11.06.2024 21:09:41 [Information] Default Save Path is Set to "C:\Users\redacted\AppData\Roaming\Changemaker Studios\Papercut SMTP"
11.06.2024 21:09:41 [Information] Loading from the Following Path(s) ["C:\Users\redacted\AppData\Roaming\Changemaker Studios\Papercut SMTP", "C:\Users\redacted\AppData\Roaming\Papercut", "C:\Program Files (x86)\Papercut SMTP\Incoming", "C:\ProgramData\Changemaker Studios\Papercut SMTP\Incoming"]
```
</details>

**Comment by Jaben** [comment]
v7.0 has been released, and this issue should be fixed. Please reopen if you continue to have any problems.
