### ISSUE TITLE
Allow installation without internet access

### ISSUE THREAD

**Issue by henkdegroot** [ChangemakerStudios/Papercut-SMTP#210]
**Describe the bug**
When I use the installer on a Windows machine which does not have internet access, it fails. I do see a powershell popup screen very briefly with red text. In windows event viewer I noticed the following text:

Product: Papercut SMTP -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action DownloadAndInvokeBootstrapper, location: C:\Program Files (x86)\Changemaker Studios\Papercut SMTP\, command: powershell.exe Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" ; & $env:TEMP\MicrosoftEdgeWebview2Setup.exe /install ; 

Because I have no internet access, I downloaded the EdgeWebView2 using another machine, copied it across and installed it (as non-admin user). The version I used is: 97.0.1072.62

The detection of the installed EdgeWebView2 fails when it has been installed as a non-admin user.

**To Reproduce**
1. Disconnect the machine from the internet
2. Run the papercut.smtp.setup.exe
3. Complete the wizard and notice it fails when it almost is complete

**Expected behavior**
Detection of the installed EdgeWebView2 component would be very helpful (even when installed as non-admin user).

**Desktop (please complete the following information):**
 - OS: Windows 2016
 - Version v1607

**Additional context**
This is not a major issue as I can just download the program and service component manually.
Note that the EdgeWebView2 component can be installed as a non-admin user, which creates the registry key (which is checked to see if the component is installed or not) in the HKEY_CURRENT_USER. When the EdgeWebView2 is installed as admin user (run as administrator), then the registry key is created in HKEY_LOCAL_MACHINE.

**Comment by henkdegroot** [comment]
Just checked the code and noticed that there is a check in the installer, I will verify why that fails on my machine.
It looks like the regkey which is being checked might have "moved" from HKLM to HKCU or perhaps the location is different depending on how the runtime was installed (as non-administrator or as administrator user).

See this link: https://stackoverflow.com/a/70652201

**Comment by 1Jesper1** [comment]
Hello @henkdegroot See these line of code: https://github.com/ChangemakerStudios/Papercut-SMTP/blob/28a5bd85c8b1ef73ba16b87909e5d4013c57f205/src/Papercut.Installer/PapercutVars.wxi#L17

Currently the reg key differs when x64 or x86.

We should implement as https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#installing-the-runtime-as-per-machine-or-per-user and check for both keys.

Would you like to create a PR?

**Comment by 1Jesper1** [comment]
@Jaben We should also fix these reg key checks on 4.8 branch https://github.com/1Jesper1/Papercut-SMTP/blob/9c0aaf4eb7954abbabd68659008a531c11f6d95f/src/Papercut.Bootstrapper/Bundle.wxs#L27

**Comment by henkdegroot** [comment]
> Would you like to create a PR?

I'll pass this time, thank you for asking.

**Comment by Jaben** [comment]
the situation is improved in the latest release -- Please try latest and reopen this issue if the problem persists.
