### ISSUE TITLE
When service restarts changes json file to default

### ISSUE THREAD

**Issue by lgrant21** [ChangemakerStudios/Papercut-SMTP#216]
Anytime the service restarts the changes to the json file revert to default. For example, changing the IP it is listening on or the location of the email files.

Steps to reproduce:
Modify JSON file
Restart service

**Comment by Jaben** [comment]
Fixed this issue in most recent commit.

**Comment by Jaben** [comment]
Please try latest and reopen this issue if the problem persists.
