### ISSUE TITLE
Log is partially under message window

### ISSUE THREAD

**Issue by cvancar** [ChangemakerStudios/Papercut-SMTP#223]
**Describe the bug**
Log window is unreadable since partially hidden under the message window, see the screenshot.

**To Reproduce**
1. In Papercut SMTP app
2. Click on Log
3. See error

**Expected behavior**
See the whole content of the Log.

**Screenshots**
![Capture-Papercut](https://user-images.githubusercontent.com/6818543/161905977-7718dab0-0fef-4c9b-8b0f-17db48e4fef2.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10  10.0.19044 Build 19044

**Comment by idblew** [comment]
Related to #198

**Comment by gilles007-** [comment]
this UI bug is still there
