### ISSUE TITLE
Welcome Message: Missing Release Notes for 6.2

### ISSUE THREAD

**Issue by GuybrushX** [ChangemakerStudios/Papercut-SMTP#226]
**Describe the bug**
Nothing too serious but the latest Release Notes for 6.2. are missing in the "Welcome to Papercut SMTP!" message (fresh install + upgrade).

**To Reproduce**
1. Install Papercut 6.2
2. Read the "Welcome to Papercut SMTP! message
3. Release Notes for 6.2 are missing

**Expected behavior**
To see the Release Notes/Change Log for 6.2 in the Welcome Message.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context**
N/A

**Comment by Jaben** [comment]
Noted -- should be fixed going forward.
