### ISSUE TITLE
Customizing the LoggingPath and MessagingPath in Papercut.Service.Settings.json file for the Papercut.Smtp.Service.6.2.0 service does not work

### ISSUE THREAD

**Issue by pcllau** [ChangemakerStudios/Papercut-SMTP#230]
**Describe the bug**
After customizing the LoggingPath and MessagingPath in Papercut.Service.Settings.json file for the Papercut.Smtp.Service.6.2.0 service, the customized paths are not recognised during the service install.

**To Reproduce**
1. Customize the LoggingPath, and MessagingPath fields in Papercut.Service.Settings.json file and save.
2. From adminstrator cmd, execute 'C:\>Papercut.Smtp.Service.6.2.0\Papercut.Service.exe install'.
3. From cmd execute 'C:\>Papercut.Smtp.Service.6.2.0\Papercut.Service.exe start'
4. See below start logs:

**Expected behavior**
The Loading and Save paths should be customized as per the changes in Papercut.Service.Settings.json file.

**Screenshots**
See screenshot of cmd install logs attached below default_install_service_always using_fixed_logging_messaging_paths.jpg
![default_install_service_always using_fixed_logging_messaging_paths](https://user-images.githubusercontent.com/30689692/191937003-75c9a070-4c71-4dad-a556-1239d62c5676.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Windows 10 Pro (Version=21H2, OS_build=19044.2006)

**Additional context**
None

**Comment by amuagarwal** [comment]
Seems development is dead as i not able to see any code change from last 3 years :(

**Comment by Jaben** [comment]
Please try latest v7.0. If you are still having problems, re-open this issue.
