### ISSUE TITLE
Papercut not functioning

### ISSUE THREAD

**Issue by vajdasagi** [ChangemakerStudios/Papercut-SMTP#240]
Hi,
I have been struggling with Papercut since early December and except of the first 2-3 days I can't convince it to function.
VERY IRRITATING!
- I installed it, went very well. The problem was that the rules had to get added every time I started the program
- I installed another version. Nothing functiones since than, but the rules are there. I can't even delete them.

I'm starting to think that this is not a serious program. Unfortunately I don't know any alternative, so I hope very much that you have some idea.
regards
Robert Keszég

**Comment by Jaben** [comment]
Thanks for letting me know. Which version are you running? What is your operating system?

**Comment by vajdasagi** [comment]
Papecut              6.2.0.0

OS                       Windows 10 pro

 

 

 

Von: Jaben Cargman ***@***.***> 
Gesendet: Donnerstag, 5. Januar 2023 21:48
An: ChangemakerStudios/Papercut-SMTP ***@***.***>
Cc: vajdasagi ***@***.***>; Author ***@***.***>
Betreff: Re: [ChangemakerStudios/Papercut-SMTP] Papercut not functioning (Issue #240)

 

Thanks for letting me know. Which version are you running? What is your operating system?

**Comment by Jaben** [comment]
Please try latest v7.0. Re-open this issue if you are still having problems.
