### ISSUE TITLE
CPU and memory consumption high when running for a long period of time

### ISSUE THREAD

**Issue by seteq** [ChangemakerStudios/Papercut-SMTP#241]
When Papercut is running for a longer period of time on my machine (several days or weeks) it consumes loads of CPU and RAM resources.
There may be some kind of memory leak, as the memory consumption is increasing continously (see task manager screenshot).

![image](https://user-images.githubusercontent.com/15156637/215227868-8528169f-505c-42d9-bba9-a8978dfe7eb4.png)

When I restart the application it consumes about 170MB of RAM and everything seems ok again.

**Comment by bangush** [comment]
WebView2 process related to Microsoft Edge.

**Comment by Payn** [comment]
Can confirm, after several hours of running in the background, it eats up whole 32GB of RAM.
Though not shown directly in Task Manager, RAMMap shows thousands of leaked "msedgewebview2.exe" processes.

**Comment by Jaben** [comment]
Should be fixed in v7.0 release. Reopen if problems continue.
