### ISSUE TITLE
Papercut is not started on Windows 11

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [ChangemakerStudios/Papercut-SMTP#242]
**Describe the bug**
After installation I tried to start  Papercut "C:\Program Files (x86)\Changemaker Studios\Papercut SMTP\Papercut.exe".
But nothing happened.
I've tried from PowereShell Admin prompt 
 start  Papercut "C:\Program Files (x86)\Changemaker Studios\Papercut SMTP\Papercut.exe".
 No any messages in event viewer

After reboot it start working, but then disappeared and I am not able to start it again without reboot.
**Desktop (please complete the following information):**
 - OS: Windows 11,  Version 22H2

**Comment by TPRuddygore** [comment]
Observation - On Windows 11, the Papercut.exe process appears to not terminate when the UI is closed OR minimized.  Subsequent attempts to start Papercut.exe fail - as another process is still running.

From task manager, finding the Papercut.exe process and then terminating it with "End task" allows it to be re-launched.

**Comment by Jaben** [comment]
Please try with latest release v7.0. Make sure and uninstall the current version of PapercutSMTP before installing the new version. Reopen this issue if you continue to have problems.
