### ISSUE TITLE
Mask passwords in rules

### ISSUE THREAD

**Issue by duckgoop** [ChangemakerStudios/Papercut-SMTP#245]
**Is your feature request related to a problem? Please describe.**
When entering passwords in rules configuration, they are displayed in clear text.

**Describe the solution you'd like**
Password masking while entering/pasting into app

**Comment by Jaben** [comment]
This is screen shot from v7 -- it's in there now:

![image](https://github.com/ChangemakerStudios/Papercut-SMTP/assets/448726/e1522d31-43db-4bc1-9c90-bcd953745ca9)
