### ISSUE TITLE
Papercut is not creating messages in the path specified in settings json file?

### ISSUE THREAD

**Issue by smartaquarius10** [ChangemakerStudios/Papercut-SMTP#253]
Hello,

I have installed papercut as window service and ran it as Local System account. I have changed the path in this variable **MessagePath** still messages are shaving in `C:\ProgramData\Changemaker Studios\Papercut SMTP\Incoming`

Is it possible to change this path in case of execution with SYSTEM account as we have a separate drive for such logs in our VM.

**Comment by Jaben** [comment]
Please try latest v7.0 and re-open this issue if you're still having problems.
