### ISSUE TITLE
Can Papercut-SMTP be used forward email?

### ISSUE THREAD

**Issue by riskyninja** [ChangemakerStudios/Papercut-SMTP#256]
Hi there, can Papercut-SMTP be used to forward emails using the rule feature?

Thanks

**Comment by mmcintyre123** [comment]
I'd like to know this too.  I want to use it to forward specific messages to my gmail.

**Comment by Jaben** [comment]
In the future both of you should just *run* the software and see for yourself:

![image](https://github.com/ChangemakerStudios/Papercut-SMTP/assets/448726/22a6151e-3e78-4076-997e-00c424ad3810)
