### ISSUE TITLE
Upgrade to .NET 8 (LTS)

### ISSUE THREAD

**Issue by danzuep** [ChangemakerStudios/Papercut-SMTP#257]
**Is your feature request related to a problem? Please describe.**
The service, WPF and Test projects are all using .NET Framework.

**Describe the solution you'd like**
You've already implemented .NET standard2.0 for the libraries, so no point in staying in the Dark Ages.

**Describe alternatives you've considered**
Downloading Framework again.

**Additional context**
It's easy to upgrade with the Microsoft .NET Upgrade Assistant extension in Visual Studio.

**Comment by leigh-pointer** [comment]
.NET 8 is a long term support (LTS) release, so upgrading to .Net8 would be better

**Comment by danzuep** [comment]
.NET 8 was still in pre-release when I opened this ticket, but yes you're right, it should be the new normal.

**Comment by Jaben** [comment]
You can download and test the .NET 8 version in this branch: https://github.com/ChangemakerStudios/Papercut-SMTP/tree/feature/net8

What's holding up the release is, as always, the installation system.
