### ISSUE TITLE
SMTP Service - Please clarify config settings

### ISSUE THREAD

**Issue by cosmic-tiger** [ChangemakerStudios/Papercut-SMTP#263]
Hello, hoping you can help clarify the settings in the service's setting json file.

"HttpBaseAddress_Description": "## The Papercut Web UI Server listening address e.g. specific hostname http://hostname (Defaults to http://127.0.0.1). If you want listen to all
hostnames use http://* . Warning: This option needs administrator permission. Please be carfully with this option for security reason! " 

Not clear on the above. Does Web UI server mean the server that is serving the inbox web page  (showing inbox, list of emails, refresh button etc)?  So what is meant by listening to all host names?

"IP_Description": "## SMTP Server listening IP. 'Any' is the default and it means '0.0.0.0'.",
"Port_Description": "## SMTP Server listening Port. Default is 25.",

Does the above refer to the actual Papercut SMTP server, or any SMTP server relay at all (not papercut) ? And there can be more than one of these and on another servers?

"IPCommServiceAddress_Description": "## The IP Comm Service IP address (Defaults to 127.0.0.1).",
"IPCommServicePort_Description": "## The IP Comm Service UI listening port (Defaults to 37403).",
"IPCommUIAddress_Description": "## The IP Comm UI IP address (Defaults to 127.0.0.1).",
"IPCommUIPort_Description": "## The IP Comm UI listening port (Defaults to 37402).",

What do the above refer to?

Thanks very much.

**Comment by Jaben** [comment]
> What do the above refer to?

IPComm = "Inter-process Communication" -- this is the server used by Papercut SMTP UI (Desktop) and Papercut SMPT Service to talk to each other. Really it's an event bus so when you update rules in the UI it updates the rules in the Service.

It will be gone soon.
