### ISSUE TITLE
Always Show

### ISSUE THREAD

**Issue by scascalespAV** [ChangemakerStudios/Papercut-SMTP#272]
Hello
Is possible to pass param to papercut to show by default? For example papercut.exe -show and run program, launch show action
Thanks

**Comment by Jaben** [comment]
Sure -- What's the use case?

**Comment by scascalespAV** [comment]
I want to launch this option on start:
![image](https://github.com/ChangemakerStudios/Papercut-SMTP/assets/110404394/6189dfc9-4998-439e-a4c0-904428c85aa0)


Not necessary to click on tray to see it

**Comment by Jaben** [comment]
So it should start like that if this option isn't selected: 

![image](https://github.com/ChangemakerStudios/Papercut-SMTP/assets/448726/4ac392b1-799f-4433-801e-774432deb472)

**Comment by scascalespAV** [comment]
ok thanks!
