### ISSUE TITLE
is it possible to run custom scripts (ex. a .bat file) on receiving emails?

### ISSUE THREAD

**Issue by yeahman45** [ChangemakerStudios/Papercut-SMTP#274]
is it possible to run custom scripts (ex. a .bat file) on receiving emails; ex. with rules?

**Comment by Jaben** [comment]
Currently, no -- but it's absolutely doable.

**Comment by Jaben** [comment]
v7.0 has this feature. Add a "Invoke Process" rule:

![image](https://github.com/user-attachments/assets/83d7a1f0-c33a-44e8-bd99-0c9ae82f5eac)

The settings are pretty simple:

![image](https://github.com/user-attachments/assets/12d09c84-cdd3-4cbc-93a3-b23af20ead91)

Closing this issue.
