### ISSUE TITLE
Cannot start service on AppVeyor

### ISSUE THREAD

**Issue by henryruhs** [ChangemakerStudios/Papercut-SMTP#44]
Hello,

I try to run Papercut on AppVeyor using `choco install papercut` but the Service does not seem to be registered or something else is wrong!?

```
papercut v4.8.0.1 [Approved]
 49papercut package files install completed. Performing other installation steps.
 50 ShimGen has successfully created a gui shim for Papercut.exe
 51 The install of papercut was successful.
 52  Software install location not explicitly set, could be in package or 
 53  default install location if installer.
 54
 55Chocolatey installed 1/1 packages. 0 packages failed.
 56 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
 57net start PapercutServerService
 58The service name is invalid.
```

Best regards
Henry

**Comment by Jaben** [comment]
Yeah, there isn't currently a papercut service for chocolately. I'll add.

**Comment by redaxmedia** [comment]
Thank you!

**Comment by redaxmedia** [comment]
Let me remind you to add `choco install papercut-service` to make life easier using AppVeyor.

**Comment by redaxmedia** [comment]
Please keep it open

**Comment by redaxmedia** [comment]
Please keep it open

**Comment by Jaben** [comment]
I have a problem with this task: can anyone show me an example of getting a service installed/running using chocolately? Thanks.

**Comment by redaxmedia** [comment]
Sorry, I never made this... not a Windows guy :-)
